name: Build and Release Go Binary

on:
  push:
    tags:
      - act-*
    # tags-ignore:
    #   - v*-alpha

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v5
      - name: Checkout CoreDNS
        uses: actions/checkout@v5
        with:
          repository: 'coredns/coredns'
          ref: 'v1.12.4'

      - name: Build
        run: |
          echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release
        uses: softprops/action-gh-release@v2
        # if: github.ref_type == 'tag'
        with:
          name: pub Name
          tag_name: "v0.0.0"

          files: |
            Release.txt
            LICENSE